version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - otherguy
  assignees:
  - otherguy
  labels:
  - "dependabot \U0001F916"
