version: 2
updates:

  # Pip packages
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
    reviewers:
      - otherguy
    assignees:
      - otherguy
    labels:
    - "dependabot \U0001F916"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - otherguy
    assignees:
      - otherguy
    labels:
    - "dependabot \U0001F916"
