version: "2"
plugins:
  git-legal:
    enabled: true
  fixme:
    enabled: true
  sonar-python:
    enabled: true
    config:
      tests_patterns:
        - tests/**
  pylint:
    enabled: true
    channel: "beta"
  editorconfig:
    enabled: true
    channel: beta
    config:
      editorconfig: .editorconfig
checks:
  similar-code:
    enabled: false
  identical-code:
    enabled: false
