name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.8.9' # Monterey default
          - '3.10' # Latest
    steps:
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v3.1.2
        with:
          python-version: '${{ matrix.python-version }}'
      - uses: actions/checkout@v3
      - run: pip install -r requirements.txt
      - run: pip install -r requirements-test.txt
      - name: 'Run tests'
        run: python -m unittest
